runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 200

runtime_config:
  python_version: 3

env_variables:
    DB_STRING: >-
      postgresql+psycopg2://postgres:asd123@/postgres?host=/cloudsql/crested-drive-277716:us-central1:nba

beta_settings:
    cloud_sql_instances: crested-drive-277716:us-central1:nba

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
